### ISSUE TITLE
Not an issue! More like a word.

### ISSUE THREAD

**Issue by loneicewolf** [odedshimon/BruteShark#138]
## Hello!
I have used BruteShark very much, and each time I discover a tool that is great, and use it for a long period of time - I always make a issue *like this one, to show my appreciation in the project. :)

Wishes from Sweden!

**Comment by odedshimon** [comment]
Hey @loneicewolf ! 
Thank you for taking the time and bringing up those kind words! Much appreciate your feedback 🙏

**Comment by loneicewolf** [comment]
By the way. You may close this 

> issue.

***

> Hey @loneicewolf ! Thank you for taking the time and bringing up those kind words! Much appreciate your feedback 

Of course, if I can't help(PullReq, Sponsor, or something) I can **at least take a break from whatever I am doing and write this issue. Doesn't take that long and is quite easy.**

Before you close this issue I have a favor to ask for:
- [x] Have a great sickness-free week! :)

***
Regards,
*Will.*

**Comment by loneicewolf** [comment]
Again, I replied to the linkedin post. It's really something else, this `BruteShark`, anyway I won't disturb more by keeping this `dead` issue `active`, but have a great day!  Sorry for the late reply too. 💯 
# `:)`
