### ISSUE TITLE
pcapng support

### ISSUE THREAD

**Issue by odedshimon** [odedshimon/BruteShark#16]
Support .pcapng file type.
Note: its better to start with checking if https://github.com/chmorgan/sharppcap is supporting pcapng.
If not, at least pop up a proper warning message (e.g. "Please convert file to pcap file type").

**Comment by NeverBit** [comment]
Hi Oded
Consider looking at [PcapngUtils ](https://github.com/ryrychj/PcapngUtils) for pcapng support.
IMO It's very intuitive and there's a .NET Standard fork by HakanL ([here](https://github.com/HakanL/PcapngUtils)) if you ever migrate to  the .NET Core/Standard combo.

**Comment by odedshimon** [comment]
Thank you for the lead, i will check it out 👍

**Comment by odedshimon** [comment]
The latest release is supporting PCAPNG files (https://github.com/odedshimon/BruteShark/releases/tag/v1.1.4)
