### ISSUE TITLE
Support with IPv6

### ISSUE THREAD

**Issue by dafan81162** [odedshimon/BruteShark#20]
When I pick a pcap with ipv6 tcp seesions, the program don't extract the password from the pcap.

**Comment by odedshimon** [comment]
Please upload / send me the pcap if possible.

**Comment by aviadtamir** [comment]
IPv6 is supported in BruteShark the problem may be a pcap file format that is still not supported in BruteShark(pcapng format for example) we will be glad if you could please attach the file which you encountered the issue with
