### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yezz123** [odedshimon/BruteShark#24]
Hey @odedshimon  i Wanna ask a simple Question what different between your project **`BruteShark`** and **`Wireshark`** ?
And thank you !

**Comment by odedshimon** [comment]
Hi @yezz123 ,
While Wireshark is a general-purpose  packet analyzer (which i think is a great tool), BruteShark is a Network Forensic Analysis Tool with a specific purpose.

The purpose of BruteShark is to provide solution to **security researchers** and network administrators with the task of network traffic analysis while they try to identify weaknesses that can be used by a potential attacker to gain access to critical points on the network. 

This is done by analyze a PCAP like a potential Hacker: looking for very specific pieces of data automatically (Hashes, Passwords) and organize them as a hacker would do (e.g. build a network map) and even integrate some data to external tools (e.g Hashcat)

**Comment by yezz123** [comment]
Thank you ! 
Now i Understand also can i Make an Analyze using one of **_linux_** distribution ?

**Comment by odedshimon** [comment]
That's true.
It is possible to run BruteShark CLI on Linux OS.
Please take a look at the project Readme, there is a full  explanation for running BruteShark on Linux (and also a video demonstration).
