### ISSUE TITLE
Windows exe file not work

### ISSUE THREAD

**Issue by amancini** [odedshimon/BruteShark#28]
Hello,

i have install BruteShark on windows OS , but it not start after installation.

on Windows event i have found error message

Description: A .NET Core application failed.
Application: BruteSharkDesktop.exe
Path: C:\Program Files (x86)\BruteSharkDesktop\BruteSharkDesktop.exe
Message: A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Program Files (x86)\BruteSharkDesktop\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

just install .NET Core SDK and it work 

i have found installer on this link
https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.401-windows-x64-installer

best regards

**Comment by odedshimon** [comment]
Hi @amancini
Thank you for sharing this issue and solution.
We will add a proper check at the installer / document it as installation requirement.
Oded.

**Comment by Stepy2005** [comment]
I conform the solution with .NET Core SDK works! Bruteshark won't start till install .NET Core SDK. Thanks!

**Comment by MrPuddinPie** [comment]
**.NET Core SDK** should be specified as a **prerequisite** for the Windows GUI version.
Had the same issue and this solved it.

**Comment by odedshimon** [comment]
@amancini @Stepy2005 @MrPuddinPie 
The project readme has been updated with *prerequisite*.
Further to that, in the future I will work on the installer project so it will be a self-contained app so * .NET Core SDK* installation will not be necessary at all. 
best regards,
Oded
