### ISSUE TITLE
CLI Linux/Windows - Option to generate network map

### ISSUE THREAD

**Issue by s3m73x** [odedshimon/BruteShark#37]
The CLI interface seems not to have an option to generate a network map.
You can show the module but not run it as it seems. Would be nice to have that option so there is no need to fiddle around with the GUI.
![bruteshark_no_network_map](https://user-images.githubusercontent.com/14231015/99191749-f974cf80-276e-11eb-8398-f83b92f7839d.png)

**Comment by odedshimon** [comment]
Hi @s3m73x,!
Thanks for creating this issue.

It is an interesting and useful feature, therefore, it will remain in BruteShark backlog, until I will have the time to implement a solution for it, hopefully soon (or someone else).

In what way would you like to see the network map? (a  JSON that can be loaded into Neo4j? Splunk? )

**Comment by odedshimon** [comment]
@s3m73x your feature request has been taken care thanks to @aviadtamir.
BruteShark v1.1.2 is now capable to export the network diagram data to a JSON file which is compatible with Neo4j (or other tools) for visualizing network diagram by analyzing a PCAP file connections. 
We would love to get your feedback's.
![Neo4j](https://user-images.githubusercontent.com/18364847/100687988-01955780-338a-11eb-97c4-6d0c51b3835a.png)
![Neo4j_3](https://user-images.githubusercontent.com/18364847/100687989-022dee00-338a-11eb-96c6-dd5bc29e6d5f.png)
