### ISSUE TITLE
Help json import on neo4j

### ISSUE THREAD

**Issue by webliqui** [odedshimon/BruteShark#45]
Hi, I have installed the tool on Linux, how can I import the json generated on neo4j to see the connection graph, like the image you entered in the tool homepage? Can you give me the commands please? Thank you!!

**Comment by odedshimon** [comment]
Hi!
There is a wiki page with the commads:
https://github.com/odedshimon/BruteShark/wiki/Neo4j-queries-for-loading-BruteShark-network-map--file
Please take a look at it

**Comment by webliqui** [comment]
Sorry but I hadn't seen this page.
Thank You!!
