### ISSUE TITLE
 An assembly specified in the application dependencies manifest (BruteSharkDesktop.deps.json) was not found

### ISSUE THREAD

**Issue by Dustie** [odedshimon/BruteShark#46]
Hello :)

I just installed Brute Shark but nothing happens at launch. I have Wireshark, Npcap, .NET SDK and .NET Core SDK installed.

From Windows event viewer:

```
Description: A .NET Core application failed.
Application: BruteSharkDesktop.exe
Path: C:\Program Files (x86)\BruteSharkDesktop\BruteSharkDesktop.exe
Message: Error:
  An assembly specified in the application dependencies manifest (BruteSharkDesktop.deps.json) was not found:
    package: 'System.Text.Json', version: '5.0.0'
    path: 'lib/netcoreapp3.0/System.Text.Json.dll'
```

**Comment by rbtoms** [comment]
I can confirm that this is an issue only in the latest release. I located the same application event in event viewer. All prior releases work as expected.

**Comment by Dustie** [comment]
Yes I just tested: It only happens in 1.1.2.

**Comment by odedshimon** [comment]
Hi, this is true, i believe there is a small bug in the installer project. This will be taken care as soon as posible.

**Comment by odedshimon** [comment]
Bug fixed, please check @Dustie @rbtoms

**Comment by rbtoms** [comment]
@odedshimon Green checks everywhere. Looks good! 👍
