### ISSUE TITLE
Additional Fields for show-networkmap / export-networkmap

### ISSUE THREAD

**Issue by vtmike88** [odedshimon/BruteShark#56]
Would it be possible to add additional packet flow fields for the  show-networkmap / export-networkmap commands? 

Specifically I'm looking for a way to add timestamp information (first packet, last packet), total number of packets and sum of data sent per flow.

**Comment by odedshimon** [comment]
Hi @vtmike88 !
I plan t implement a shared context for all the entities extracted (e.g. sessions, host, credentials etc).

Once that context will be implemented, all the relevant entitles related to a host could be exported including sessions (and as part of that also the the above insights could be achieved).

I will consider this suggestion during the design. thanks for uploading it.

Oded.

**Comment by odedshimon** [comment]
Hi @vtmike88,
I have implemented a shared context for all the entities extracted and added some additional fields to the network map:

- open ports
- DNS records
- Sessions count 

The exported files including a new file named **"BruteShark Network Nodes Data.json"** that holds all the nodes details (You can take a look at the latest release).

I can add the the first packet / last packet time and total number of packets pretty easily is it still be useful for you?

**Comment by odedshimon** [comment]
Examples: 
![NodeDetails2](https://user-images.githubusercontent.com/18364847/134251590-c2adb25f-8022-4582-95ec-bd28c1aff78b.png)
![133478184-7bb28c3f-24d7-4b4f-b54d-5c9d3f59f3eb (1)](https://user-images.githubusercontent.com/18364847/134251620-4102a403-a2f9-4784-b10b-5c81007c22a8.png)

**Comment by odedshimon** [comment]
You haven't respond me but yet I have added some more fields that I thought they would be useful, not everything you asked for but I considered your suggestion:

1. Sent data - The amount of data (bytes) sent by the host.
2. Received data - The amount of data received (bytes) by the host.
3. Domains - the domains that the host is a member of.
4. Domain users - domain users that logged into the host.

This fields will also appear at the **"BruteShark Network Nodes Data.json"** file that holds all the nodes details.
This change will take place at the **next release**.

Examples:
![NodeDetails](https://user-images.githubusercontent.com/18364847/135112386-baf563d9-7155-40a8-ac90-302adf757f78.png)
![NodeDetailsJson](https://user-images.githubusercontent.com/18364847/135112424-b4b4cfe8-9779-4d40-b85a-56bda39a5860.png)
:
