### ISSUE TITLE
.exe Dont work

### ISSUE THREAD

**Issue by Lorekin** [odedshimon/BruteShark#57]
Npcap and .NET SDK installed
![ConEmu64_4iJ745oeAW](https://user-images.githubusercontent.com/26692817/103309695-ce94c100-4a26-11eb-9ab3-40a12f0b22bf.png)

**Comment by odedshimon** [comment]
Hi @Lorekin,
You are right, a missing DLL file. 
I will fix it.
Thank you.

**Comment by odedshimon** [comment]
You can now download the installer again, it should work
