### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cgoat** [odedshimon/BruteShark#77]
Can we add an option of adding more features to the JSON file. Right now i see the Source, Destination, Protocol, SrcPort, DestPort.  Other options can be details about the packet itself (Time, Sequence Number, Flags etc..). I am trying to build a graph in neo4j.

I currently am able to create a graph with the code below

WITH  "file:///home/xxx/dump/output.json" AS url 
CALL apoc.load.json(url) 
YIELD value AS NetworkTraffic
UNWIND NetworkTraffic AS items
MERGE (s:Packet{id: items.Source, protocol:items.Prtocol, Srcport:Items.SrcPort})
MERGE (d:Packet{id: items.Destination, Destport:Items.DestPort})
CREATE (s) -[r:connects]->(d)
RETURN s,d,r;

![NEO4J](https://user-images.githubusercontent.com/33079901/105942764-7cdf5680-6025-11eb-8958-10347f280306.PNG)

**Comment by odedshimon** [comment]
Hi @cgoat,
Thanks you for your suggestion.
I found it a usefull feature and it will be implemented in the next releases - so keep follow 😃 
Cheers, 
Oded.

**Comment by odedshimon** [comment]
Hi @cgoat 
I have implemented a massive refactor to handle this feature.
Network Map user control now have a control describes the node details (open ports, DNS records, sessions count)
The exported files including a new file named "BruteShark Network Nodes Data.json" that holds all the nodes details.

**That will be take place at next release**

Thanks you for your suggestion :-)

![image](https://user-images.githubusercontent.com/18364847/133474896-2c8b97b6-1312-4ad0-aee6-ec4d85ee3837.png)
![NodeDetails2](https://user-images.githubusercontent.com/18364847/133474956-bb639ac9-6de0-42e0-a1f8-6291da9c3b01.png)
