### ISSUE TITLE
Double clicking on it does nothing at all WIN 10

### ISSUE THREAD

**Issue by minanagehsalalma** [odedshimon/BruteShark#84]
version 1909 build 18363.1379

i have wireshark and it works perfectly if that helps .

**Comment by odedshimon** [comment]
There was a small bug with the release, I have fixed it.
Thanks for letting me know.
You can now re install the version, the latest release was updated.
Please update if that worked for you

**Comment by minanagehsalalma** [comment]
@odedshimon nothing changed update the msi file pls.

**Comment by odedshimon** [comment]
@minanagehsalalma ,
Did you re installed it? (control panel -> add or remove programs, download msi again and installing it)?
What is your .Net Core version? 
Which version of Windows do you use?

**Comment by minanagehsalalma** [comment]
@odedshimon mate you haven't updated it :/
![image](https://user-images.githubusercontent.com/20546638/110959232-28cece00-8356-11eb-8fa4-eb1261f3efb0.png)

**Comment by odedshimon** [comment]
@minanagehsalalma 
I did.
I edited the release by replacing the msi file with a new msi including the bug fix - **therefore the release date didn't changed.** 
Please upload a picture of the BruteShark version installed on your PC (control panel -> add or remove programs), **it should be 1.2.7.0** (the former was 1.2.6.0). 
![image](https://user-images.githubusercontent.com/18364847/111005455-846b7c80-8393-11eb-97ec-f65addad4c92.png)

**Comment by minanagehsalalma** [comment]
@odedshimon 
![image](https://user-images.githubusercontent.com/20546638/111051802-746c9f00-845e-11eb-9377-beab18ff18fb.png)

**Comment by PoTskiii** [comment]
I have the same issue...

**Comment by odedshimon** [comment]
Thank you @PoTskiii .
I will update the readme to be more clear about it.
Also i will try to enforce it at the msi file (there is already an issue about it #63 )

**Comment by odedshimon** [comment]
readme file was updated with a link to .NET Core Runtime 3.1 as prerequisite.
