### ISSUE TITLE
Input "start",there was nothing happened with BruteSharkCli.

### ISSUE THREAD

**Issue by bopin2020** [odedshimon/BruteShark#86]
![image](https://user-images.githubusercontent.com/49940777/110725306-57fc1700-8252-11eb-80b6-c2bc371fa171.png)

After inputing add-file some examples *pcap files in ubuntu1604 console and Windows WSLv2 console. it seems as if dead:) I'm curious about nothing happened. I dont know how to solve this trouble.

**Comment by bopin2020** [comment]
Stupid mistakes:) emmm. Thank you!

**Comment by odedshimon** [comment]
@bopin2020 ,
I prefer mistakes over bugs 😸 Cheers!
Feel free to use, learn and contribute to this project.
Oded
