### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by ChamDK** [odedshimon/BruteShark#87]
installed the exe, cant even open the program, no errors, just nothing on the screen.
EDIT: got it working
However it do not show the hashes of kerberos.

**Comment by odedshimon** [comment]
Hi @ChamDK !
I will need the PCAP files to debug it, please attach them to this thread or send them to my mail (contact.oded.shimon@gmail.com).
If you don't want to send the file, feel free to debug it yourself (I accept Pull-Requests).
Oded.

**Comment by aviadtamir** [comment]
Hi @ChamDK , sounds like you need to install .net core runtime on your machine, download it from here:
https://dotnet.microsoft.com/download#:~:text=.NET%20Core-,.NET%20Core%20is%20a%20free%2C%20cross-platform%2C%20open,many%20different%20types%20of%20applications.

**Comment by odedshimon** [comment]
@ChamDK Since you have not reply, I'm closing the issue.

**Comment by odedshimon** [comment]
@ChamDK Fixed.
(https://github.com/odedshimon/BruteShark/issues/90)
