### ISSUE TITLE
who can give an example of PcapAnalyzer Modules which using  Packet.Net  to  analyse pcap files?

### ISSUE THREAD

**Issue by herotheo** [odedshimon/BruteShark#92]
谁有PcapAnalyzer的Modules例子，使用Packet.Net进行pcap 文件分析？

**Comment by odedshimon** [comment]
Hi @herotheo,
I'm not sure I understand the question.
Anyway, if you want to create a new module, you just need to implement the IModule interface (https://github.com/odedshimon/BruteShark/blob/master/BruteShark/PcapAnalyzer/Modules/IModule.cs).
You can take a look at the other modules for inspiration.
Oded.
