### ISSUE TITLE
Clear the analyzed data, re-analyze again, and re-assign

### ISSUE THREAD

**Issue by qq1176914912** [odedshimon/BruteShark#95]
I have a question. I want to clear the results of the analysis, and then re-analyze the assignment. Now there is only NetworkMap, I don't know how to solve it. When I clear the data and analyze the allocation again, the NetworkMap is blank and will not be assigned again. how to solve this problem?

**Comment by odedshimon** [comment]
Hi @qq1176914912!
At this moment there is no mechanism for clearing the data, though it a good feature.
I hope I will get to it soon.
If you feel like implementing it by yourself, feel free to fork and pull request the changes.
Thanks. Oded.

**Comment by odedshimon** [comment]
Anyway as a temporary solution, you can always reboot the app and re-analyze the files

**Comment by qq1176914912** [comment]
Ok thanks for reply

**Comment by odedshimon** [comment]
@qq1176914912 
Following your request, the feature has been implemented and will be present at next release.
![image](https://user-images.githubusercontent.com/18364847/129493338-93383fe7-4708-47c5-850d-cbec31f7be4e.png)
