### ISSUE TITLE
Unable to run GUI in Windows 10

### ISSUE THREAD

**Issue by bishwanaren** [odedshimon/BruteShark#96]
Hi, For some reason, I'm not able to run the GUI in windows 10, But CLI works, Kindly let me know it supports Windows 10 and how to resolve as it doesn't start.

**Comment by odedshimon** [comment]
Hi @bishwanaren !
It can run on Windows 10.
Have you installed al the prerequisites? 
Which version of .NetCore is installed on your computer?

**Comment by richardcurteis** [comment]
I have this same issue, fresh install on Win10 and Wireshark (for winpcap) with .NET Core 3.1.17 x64

**Comment by odedshimon** [comment]
Thank you @richardcurteis!
That's make sense. 
I will update the prerequisites at the readme to be more clear about it.
