### ISSUE TITLE
Runing error?

### ISSUE THREAD

**Issue by Shanzem** [odedshimon/BruteShark#99]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
SharpPcap.PcapException: Error setting PcapDevice mode. : driver error: working mode not recognized
   at SharpPcap.Npcap.NpcapDevice.set_Mode(CaptureMode value)
   at PcapProcessor.Sniffer.StartSniffing(CancellationToken ct)
   at BruteSharkDesktop.MainForm.<>c__DisplayClass35_0.<StartLiveCaptureAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at BruteSharkDesktop.MainForm.StartLiveCaptureAsync()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.21.35901
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Private.CoreLib.dll
----------------------------------------
BruteSharkDesktop
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/BruteSharkDesktop.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.35902
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.InteropServices.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.Extensions.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Diagnostics.Debug.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.Tasks.dll
----------------------------------------
PcapAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/PcapAnalyzer.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/netstandard.dll
----------------------------------------
PcapProcessor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/PcapProcessor.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.2.2
    Win32 Version: 4.700.21.6905
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.35902
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/Accessibility.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.NonGeneric.dll
----------------------------------------
System.Memory
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Memory.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.IO.FileSystem.dll
----------------------------------------
PacketDotNet
    Assembly Version: 1.1.2.0
    Win32 Version: 1.1.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/PacketDotNet.dll
----------------------------------------
System.Linq
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Linq.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 4.0.3.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Resources.ResourceManager.dll
----------------------------------------
System.Resources.Writer
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Resources.Writer.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Text.RegularExpressions.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Buffers.dll
----------------------------------------
System.Xml.XDocument
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Xml.XDocument.dll
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Private.Xml.Linq.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Private.Xml.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Private.Uri.dll
----------------------------------------
Microsoft.Msagl.GraphViewerGdi
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/Microsoft.Msagl.GraphViewerGdi.dll
----------------------------------------
AutomaticGraphLayout.Drawing
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/AutomaticGraphLayout.Drawing.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/mscorlib.dll
----------------------------------------
AutomaticGraphLayout
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/AutomaticGraphLayout.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.35902
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.15.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/System.Windows.Extensions.dll
----------------------------------------
CommonUi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/CommonUi.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.18/System.Resources.Extensions.dll
----------------------------------------
SharpPcap
    Assembly Version: 5.4.0.0
    Win32 Version: 5.4.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/BruteSharkDesktop/SharpPcap.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Net.Primitives.dll
----------------------------------------
System.Net.NetworkInformation
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Net.NetworkInformation.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.ThreadPool.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.5.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.5.0
    Win32 Version: 4.700.21.36305
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

I installed the x64 .Net core via the link!  Win32 Version: 4.700.21.36305???????

**Comment by odedshimon** [comment]
Hi @Shanzem,
I didn't understand your problem.
Please add a detailed description of the problem including examples.
Oded.

**Comment by Shanzem** [comment]
Ok gimmie a min and thank you!

**Comment by Shanzem** [comment]
Ok the program loads up just fine.

I followed the instructions and already have pcap installed from wireshark :) Downloaded the latest vision just to be sure.
I then downloaded the x64 .net 3.0 runtime and installed and rebooted.

I then downloaded the pre built 64bit binary package and installed.

Now using the module DNS and network mapping i get the error above when i click capture on wifi.

![BruteSharkError](https://user-images.githubusercontent.com/36472755/130353377-e5157da9-d9d8-4d1b-824b-7b561cddeb24.jpg)

I am using windows 10 with WSL2 and my system is currently running the latest windows updates.

Should i try installing the x86 (32bit) package? Little odd i know :/

**Comment by Shanzem** [comment]
![WindowsNET30](https://user-images.githubusercontent.com/36472755/130354587-be95626a-7677-44c7-85c0-2b9bfb31d8d8.png)

**Comment by odedshimon** [comment]
Thanks for the detailed description.
Since the app is launching just fine I tend to believe it is a bug at the only at the sniffing flow or at SharpPcap library (one of the major packages BruteShark is using).

For isolating the reason it would be great if you check some offline analysis by loading some PCAP files (you can get those from this repo at - https://github.com/odedshimon/BruteShark/tree/master/Pcap_Examples)

**Comment by Shanzem** [comment]
On it! Will check and report back.

**Comment by Shanzem** [comment]
Huston we have a problem.... they work as intended!

![pop3](https://user-images.githubusercontent.com/36472755/130544990-97dc8f86-b726-4251-b069-f9e3d1e13b1a.jpg)
![tcip5](https://user-images.githubusercontent.com/36472755/130545001-6f3d7432-1a2c-4228-92f2-4184925fc94b.png)
![htmlsmallfile](https://user-images.githubusercontent.com/36472755/130545040-573598fa-46be-4e34-925a-56ec155bc726.jpg)

**Comment by qq1176914912** [comment]
> 休斯顿，我们遇到了问题……它们按预期工作！
> 
> ![流行音乐3](https://user-images.githubusercontent.com/36472755/130544990-97dc8f86-b726-4251-b069-f9e3d1e13b1a.jpg)
> ![tcip5](https://user-images.githubusercontent.com/36472755/130545001-6f3d7432-1a2c-4228-92f2-4184925fc94b.png)
> ![html小文件](https://user-images.githubusercontent.com/36472755/130545040-573598fa-46be-4e34-925a-56ec155bc726.jpg)

I also encountered this problem. The npcap1.31 version can capture packets normally but cannot capture the data. The latest version of npcap 1.51 will report an error when it starts.
![S7YM)~AUD%R~4KHOY94J}41](https://user-images.githubusercontent.com/79817742/130710091-2479d1c0-b464-462f-92a2-d5405c3680c5.png)
![)WNEXMZKO%$OO}KYDPU 2AF](https://user-images.githubusercontent.com/79817742/130710102-15548022-f4b3-44f9-bcb8-810d45bb8686.png)

**Comment by odedshimon** [comment]
Hi @qq1176914912 , @Shanzem 
The problem you have described happened to me too. There seems to be a problem with the sniffing wireless interfaces (I sniffed successfuly  an Ethernet interfaces), after short debugging it seems that the Sniffer class does not manage to capture any packets, I think it is related to the SharpPcap library that BruteShark is using. I will open an issue at SharpPcap repo for discussing this issue and look for solution.

**Comment by odedshimon** [comment]
There was no bug with capturing wireless interfaces, **there was a bug caused that although a certain network interface was selected at the user interface, another network card was selected behind the scenes**.
At first I thought it was a problem with capturing wireless network interfaces only, but in fact the phenomenon could happen with any network interface.
**Bug fixed and merged to master** and will be included at the next release (Will be published in the coming days)

Thanks for letting me know! @Shanzem, @qq1176914912

**Comment by qq1176914912** [comment]
> 没有捕获无线接口**的bug**，**有一个bug导致虽然在用户界面选择了某个网络接口，但在幕后选择了另一个网卡**。
> 一开始我以为是只捕获无线网络接口的问题，但实际上任何网络接口都会出现这种现象。
> **修复了错误并合并到 master**并将包含在下一个版本中（将在未来几天发布）
> 
> 谢谢你让我知道！@Shanzem , @qq1176914912

You're welcome, let's make the program more perfect together
